import {
  Student,
  ServiceRequest,
  ExamAccommodation,
  InstitutionAudit,
  ComplianceRequirement,
  InstitutionComplianceRecord,
  IncidentReport,
  GovernancePolicy,
  ActionItem,
  AIRecommendation,
  NotificationItem,
} from '@/types';

export const mockInstitutions = [
  { id: 'inst-01', name: 'Government Institute of Inclusive Science, Mumbai', district: 'Mumbai Suburban', code: 'MH-MUM-101' },
  { id: 'inst-02', name: 'Dr. B.R. Ambedkar National Inclusive Academy, Pune', district: 'Pune', code: 'MH-PUN-204' },
  { id: 'inst-03', name: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur', district: 'Nagpur', code: 'MH-NAG-309' },
  { id: 'inst-04', name: 'Savitribai Phule Special Girls Academy, Nashik', district: 'Nashik', code: 'MH-NSK-412' },
  { id: 'inst-05', name: 'Rajarshi Shahu Accessible Technical Institute, Kolhapur', district: 'Kolhapur', code: 'MH-KOP-515' },
];

export const mockStudents: Student[] = [
  {
    id: 'std-001',
    rollNumber: 'INC-2026-001',
    fullName: 'Aarav Sharma',
    age: 16,
    grade: 'Grade 11',
    section: 'A - Science',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    guardianName: 'Rajesh Sharma',
    guardianPhone: '+91 98765 43210',
    guardianEmail: 'rajesh.sharma@example.com',
    emergencyContact: '+91 98765 43211',
    disabilityPercentage: 75,
    udidCardNumber: 'MH14001200800192',
    academicPerformanceScore: 88,
    supportHistoryCount: 14,
    activeAccommodationsCount: 4,
    ilpStatus: 'approved',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-001',
      studentId: 'std-001',
      categories: ['visual'],
      primaryCategory: 'visual',
      severity: 'severe',
      communicationPreference: 'audio',
      learningFormatPreference: 'text_to_speech',
      examinationFormatPreference: 'scribe',
      assistiveTechNeeded: ['Screen Reader (NVDA)', 'Refreshable Braille Display', 'Audio Calculator'],
      classroomAccommodationsNeeded: ['Front row seating', 'High contrast printouts', 'Audio recorded lectures'],
      digitalAccommodationsNeeded: ['Accessible Screen Reader PDFs', 'Dark mode high contrast UI'],
      transportationNeeded: true,
      updatedAt: '2026-08-10',
    },
  },
  {
    id: 'std-002',
    rollNumber: 'INC-2026-002',
    fullName: 'Ananya Deshmukh',
    age: 15,
    grade: 'Grade 10',
    section: 'B - Arts',
    institutionId: 'inst-02',
    institutionName: 'Dr. B.R. Ambedkar National Inclusive Academy, Pune',
    guardianName: 'Priya Deshmukh',
    guardianPhone: '+91 98220 11223',
    guardianEmail: 'priya.d@example.com',
    emergencyContact: '+91 98220 11224',
    disabilityPercentage: 80,
    udidCardNumber: 'MH12009200900481',
    academicPerformanceScore: 92,
    supportHistoryCount: 9,
    activeAccommodationsCount: 3,
    ilpStatus: 'approved',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-002',
      studentId: 'std-002',
      categories: ['hearing', 'speech'],
      primaryCategory: 'hearing',
      severity: 'severe',
      communicationPreference: 'sign_language',
      learningFormatPreference: 'audio_visual',
      examinationFormatPreference: 'digital_accessible',
      assistiveTechNeeded: ['Hearing Aids', 'Real-time Captioning Software', 'ISL Interpreter App'],
      classroomAccommodationsNeeded: ['ISL Sign Language Interpreter', 'Live Captions on Screen'],
      digitalAccommodationsNeeded: ['Subtitled Video Lectures', 'Visual Bell & Alerts'],
      transportationNeeded: false,
      updatedAt: '2026-08-12',
    },
  },
  {
    id: 'std-003',
    rollNumber: 'INC-2026-003',
    fullName: 'Rohan Kulkarni',
    age: 17,
    grade: 'Grade 12',
    section: 'C - Commerce',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    guardianName: 'Suresh Kulkarni',
    guardianPhone: '+91 99300 44556',
    guardianEmail: 'suresh.k@example.com',
    emergencyContact: '+91 99300 44557',
    disabilityPercentage: 60,
    udidCardNumber: 'MH14002200700883',
    academicPerformanceScore: 81,
    supportHistoryCount: 11,
    activeAccommodationsCount: 3,
    ilpStatus: 'active',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-003',
      studentId: 'std-003',
      categories: ['mobility'],
      primaryCategory: 'mobility',
      severity: 'moderate',
      communicationPreference: 'standard',
      learningFormatPreference: 'interactive',
      examinationFormatPreference: 'extra_time',
      assistiveTechNeeded: ['Motorized Wheelchair', 'Ergonomic Desk'],
      classroomAccommodationsNeeded: ['Ground floor seating', 'Ramp accessible lab', 'Accessible washroom access'],
      digitalAccommodationsNeeded: ['On-screen keyboard support'],
      transportationNeeded: true,
      updatedAt: '2026-08-14',
    },
  },
  {
    id: 'std-004',
    rollNumber: 'INC-2026-004',
    fullName: 'Diya Patil',
    age: 14,
    grade: 'Grade 9',
    section: 'A - Science',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    guardianName: 'Sunil Patil',
    guardianPhone: '+91 94221 88776',
    guardianEmail: 'sunil.p@example.com',
    emergencyContact: '+91 94221 88777',
    disabilityPercentage: 45,
    udidCardNumber: 'MH31005201000319',
    academicPerformanceScore: 76,
    supportHistoryCount: 7,
    activeAccommodationsCount: 2,
    ilpStatus: 'under_review',
    ispStatus: 'active',
    accessibilityProfile: {
      id: 'ap-004',
      studentId: 'std-004',
      categories: ['learning_difficulties', 'neurodiverse'],
      primaryCategory: 'learning_difficulties',
      severity: 'moderate',
      communicationPreference: 'simplified_text',
      learningFormatPreference: 'simplified_syntax',
      examinationFormatPreference: 'extra_time',
      assistiveTechNeeded: ['Text-Simplifier AI Assistant', 'Read&Write Software'],
      classroomAccommodationsNeeded: ['Extra time on assignments', 'Visual task schedules', 'Quiet study corner'],
      digitalAccommodationsNeeded: ['OpenDyslexic Font mode', 'Break down long paragraphs'],
      transportationNeeded: false,
      updatedAt: '2026-08-15',
    },
  },
];

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: 'sr-101',
    ticketNumber: 'REQ-2026-8801',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionId: 'inst-01',
    serviceType: 'scribe',
    title: 'Certified Scribe Request for Grade 11 Mid-Term Physics & Chemistry Exams',
    description: 'Student requires a certified scribe proficient in Science notation for upcoming mid-term exams starting Aug 25.',
    urgency: 'high',
    status: 'under_review',
    requestedBy: 'Rajesh Sharma (Parent)',
    createdAt: '2026-08-18 10:30',
    updatedAt: '2026-08-18 11:15',
  },
  {
    id: 'sr-102',
    ticketNumber: 'REQ-2026-8802',
    studentId: 'std-002',
    studentName: 'Ananya Deshmukh',
    institutionId: 'inst-02',
    serviceType: 'sign_language_interpreter',
    title: 'ISL Interpreter Request for Annual Science Exhibition',
    description: 'Requires Indian Sign Language interpreter during live project presentations.',
    urgency: 'medium',
    status: 'approved',
    requestedBy: 'Priya Deshmukh (Parent)',
    assignedToStaffName: 'Prof. Smita Joshi (ISL Coordinator)',
    createdAt: '2026-08-16 14:20',
    updatedAt: '2026-08-17 09:00',
  },
  {
    id: 'sr-103',
    ticketNumber: 'REQ-2026-8803',
    studentId: 'std-003',
    studentName: 'Rohan Kulkarni',
    institutionId: 'inst-01',
    serviceType: 'transportation',
    title: 'Wheelchair Accessible Van Request for Daily Campus Transit',
    description: 'Requesting wheelchair-accessible ramp bus pickup from Ghatkopar metro station.',
    urgency: 'medium',
    status: 'in_progress',
    requestedBy: 'Rohan Kulkarni (Student)',
    assignedToStaffName: 'Vijay Shinde (Transport Supervisor)',
    createdAt: '2026-08-12 16:45',
    updatedAt: '2026-08-15 12:00',
  },
];

export const mockExamAccommodations: ExamAccommodation[] = [
  {
    id: 'ea-301',
    examName: 'Mid-Term Board Physics Paper 1',
    subjectCode: 'PHY-101',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionId: 'inst-01',
    examDate: '2026-08-25',
    extraTimeMinutes: 40,
    scribeNeeded: true,
    scribeAssignedName: 'Vikram Mehta (M.Sc Physics)',
    readerNeeded: true,
    interpreterNeeded: false,
    alternativePaperNeeded: false,
    status: 'approved',
    invigilatorNotes: 'Scribe verified. Audio recording permitted in Room 104 Accessibility Lab.',
  },
  {
    id: 'ea-302',
    examName: 'Mathematics Annual Paper',
    subjectCode: 'MATH-202',
    studentId: 'std-002',
    studentName: 'Ananya Deshmukh',
    institutionId: 'inst-02',
    examDate: '2026-08-28',
    extraTimeMinutes: 30,
    scribeNeeded: false,
    readerNeeded: false,
    interpreterNeeded: true,
    alternativePaperNeeded: true,
    status: 'allocated',
    invigilatorNotes: 'Visual question paper provided. ISL interpreter present during instructions.',
  },
];

export const mockAudits: InstitutionAudit[] = [
  {
    id: 'aud-501',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    district: 'Mumbai Suburban',
    auditorId: 'aud-09',
    auditorName: 'Dr. Ramesh Nambiar (Certified Accessibility Auditor)',
    auditDate: '2026-08-05',
    overallScore: 89,
    riskLevel: 'low',
    status: 'verified',
    checklistItems: [
      { id: 'ck-1', category: 'entrance', title: 'Main Entrance Ramp & Tactile Paving', description: 'Ramp slope < 1:12 with continuous handrails and tactile guiding path.', isCompliant: true, score: 9.5 },
      { id: 'ck-2', category: 'digital', title: 'Website & Student Portal Screen Reader Compliance', description: 'WCAG 2.1 AA certified with full keyboard navigation.', isCompliant: true, score: 9.0 },
      { id: 'ck-3', category: 'washroom', title: 'Accessible Gender-Neutral Washrooms', description: 'Grab bars, emergency pull cord, sliding doors on ground & 1st floors.', isCompliant: true, score: 8.5 },
      { id: 'ck-4', category: 'laboratory', title: 'Adjustable Height Science Laboratory Benches', description: 'Motorized height adjustable benches for wheelchair users.', isCompliant: true, score: 9.0 },
      { id: 'ck-5', category: 'emergency', title: 'Strobe Light & Tactile Emergency Alarms', description: 'Visual strobe lights in all classrooms and auditory chime in corridors.', isCompliant: false, score: 5.0, notes: 'Missing strobe light in 3rd floor chemistry lab.' },
    ],
  },
  {
    id: 'aud-502',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    district: 'Nagpur',
    auditorId: 'aud-12',
    auditorName: 'Sunita Rao (District Inspector)',
    auditDate: '2026-08-11',
    overallScore: 68,
    riskLevel: 'high',
    status: 'submitted',
    checklistItems: [
      { id: 'ck-201', category: 'entrance', title: 'Main Entrance Ramp', description: 'Steep ramp lacking braille signage.', isCompliant: false, score: 4.0 },
      { id: 'ck-202', category: 'washroom', title: 'Accessible Washrooms', description: 'Locked washroom converted to storage.', isCompliant: false, score: 2.0 },
    ],
  },
];

export const mockComplianceRequirements: ComplianceRequirement[] = [
  { id: 'cr-01', code: 'RPWD-SEC-16', title: 'Duty of Educational Institutions regarding Inclusive Education', legalReference: 'Rights of Persons with Disabilities Act 2016 - Section 16', category: 'physical_access', mandatoryLevel: 'essential', evidenceType: 'audit_report' },
  { id: 'cr-02', code: 'RPWD-SEC-17', title: 'Specific measures to promote and facilitate inclusive education', legalReference: 'RPWD Act 2016 - Section 17', category: 'academic_accommodation', mandatoryLevel: 'essential', evidenceType: 'document' },
  { id: 'cr-03', code: 'UGC-A11Y-2023', title: 'Guidelines for Accessible Higher Education & Digital Infrastructure', legalReference: 'UGC Notification 2023', category: 'digital_access', mandatoryLevel: 'essential', evidenceType: 'certificate' },
];

export const mockComplianceRecords: InstitutionComplianceRecord[] = [
  { id: 'icr-1', institutionId: 'inst-01', institutionName: 'Government Institute of Inclusive Science, Mumbai', requirementId: 'cr-01', requirementTitle: 'Duty of Educational Institutions regarding Inclusive Education', status: 'compliant', verifiedBy: 'Auditor Nambiar', verifiedAt: '2026-08-06' },
  { id: 'icr-2', institutionId: 'inst-01', institutionName: 'Government Institute of Inclusive Science, Mumbai', requirementId: 'cr-03', requirementTitle: 'Guidelines for Accessible Higher Education & Digital Infrastructure', status: 'compliant', verifiedBy: 'Auditor Nambiar', verifiedAt: '2026-08-06' },
  { id: 'icr-3', institutionId: 'inst-03', institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur', requirementId: 'cr-01', requirementTitle: 'Duty of Educational Institutions regarding Inclusive Education', status: 'non_compliant', correctiveActionPlan: 'Construct standard 1:12 ramp and install braille handrails.', deadline: '2026-09-30' },
];

export const mockIncidents: IncidentReport[] = [
  {
    id: 'inc-901',
    caseNumber: 'INC-2026-041',
    category: 'accessibility_denial',
    isAnonymous: false,
    reporterId: 'std-003',
    reporterRole: 'student',
    victimStudentId: 'std-003',
    institutionId: 'inst-01',
    title: 'Elevator Out of Service Blocking Access to 3rd Floor Computer Lab',
    description: 'Elevator B in Block C has been broken for 4 days, preventing wheelchair users from attending practical exams.',
    location: 'Block C Elevator B',
    dateOfIncident: '2026-08-17',
    severity: 'severe',
    status: 'under_investigation',
    investigatingOfficerName: 'Er. Rajesh Varma (Facility Head)',
    createdAt: '2026-08-17 11:30',
  },
  {
    id: 'inc-902',
    caseNumber: 'INC-2026-042',
    category: 'bullying',
    isAnonymous: true,
    institutionId: 'inst-03',
    title: 'Verbal Harassment regarding Hearing Aid Usage',
    description: 'Reported inappropriate mocking of a hearing impaired student during lunch break.',
    location: 'Cafeteria Wing A',
    dateOfIncident: '2026-08-15',
    severity: 'moderate',
    status: 'action_taken',
    investigatingOfficerName: 'Dr. Meena Iyer (Counselor)',
    resolutionSummary: 'Counseling session conducted with class students. Awareness drive scheduled.',
    createdAt: '2026-08-15 15:10',
  },
];

export const mockPolicies: GovernancePolicy[] = [
  { id: 'pol-01', policyNumber: 'POL-A11Y-2026-01', title: 'Universal Accommodation & Scribe Guidelines 2026', category: 'exam_rules', effectiveDate: '2026-01-01', version: '2.4', approvedBy: 'State Board Governance Council', status: 'active' },
  { id: 'pol-02', policyNumber: 'POL-A11Y-2026-02', title: 'Digital Learning Material Accessibility Policy', category: 'accessibility_standard', effectiveDate: '2026-03-15', version: '1.2', approvedBy: 'Department of Inclusive Education', status: 'active' },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: 'air-1',
    type: 'accessibility_gap',
    title: 'High Exam Scribe Demand Predicted for Upcoming Mid-Terms',
    description: 'AI model detected 28 pending scribe requests in Mumbai District. Recommended assigning 12 additional certified scribes to prevent bottlenecks.',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    confidenceScore: 94,
    suggestedAction: 'Auto-allocate 12 verified postgraduate volunteer scribes to exam room 104 & 105.',
    status: 'pending_review',
    createdAt: '2026-08-18 08:00',
  },
  {
    id: 'air-2',
    type: 'risk_alert',
    title: 'Compliance Risk Alert: Elevator Maintenance Delay in Nagpur School',
    description: 'Chhatrapati Shivaji Secondary School compliance score fell to 68%. Elevated risk of RPWD Section 16 non-compliance notice.',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    confidenceScore: 91,
    suggestedAction: 'Issue immediate corrective action notice with 15-day remediation deadline.',
    status: 'pending_review',
    createdAt: '2026-08-17 16:30',
  },
];

export const mockNotifications: NotificationItem[] = [
  { id: 'notif-1', title: 'Scribe Request Approved', message: 'Your scribe request for Physics Paper 1 has been approved.', type: 'success', targetRoles: ['student', 'parent'], timestamp: '10 mins ago', isRead: false },
  { id: 'notif-2', title: 'Audit Report Submitted', message: 'Annual Accessibility Audit for Institute #101 is now available for review.', type: 'info', targetRoles: ['auditor', 'principal', 'institution_admin', 'district_officer'], timestamp: '1 hour ago', isRead: false },
  { id: 'notif-3', title: 'Action Required: Ramp Inspection', message: 'Remediation deadline for Ramp signage in Block B expires in 3 days.', type: 'warning', targetRoles: ['institution_admin', 'accessibility_coordinator'], timestamp: '3 hours ago', isRead: true },
];
