import {
  Student,
  ServiceRequest,
  ExamAccommodation,
  InstitutionAudit,
  ComplianceRequirement,
  InstitutionComplianceRecord,
  IncidentReport,
  GovernancePolicy,
  ActionItem,
  AIRecommendation,
  NotificationItem,
} from '@/types';

export const mockInstitutions = [
  { id: 'inst-01', name: 'Jamshedpur Special Education & Technical Institute', district: 'East Singhbhum (Jamshedpur)', code: 'JH-JSR-101', totalStudents: 142, complianceScore: 92.4, status: 'Active', category: 'Special Higher Technical Education' },
  { id: 'inst-02', name: 'Ranchi Government Inclusive Model High School', district: 'Ranchi', code: 'JH-RNC-102', totalStudents: 188, complianceScore: 88.5, status: 'Active', category: 'Government Secondary School' },
  { id: 'inst-03', name: 'Dhanbad Accessible Higher Secondary School', district: 'Dhanbad', code: 'JH-DHN-103', totalStudents: 96, complianceScore: 84.2, status: 'Active', category: 'Higher Secondary Institute' },
  { id: 'inst-04', name: 'Bokaro Inclusive Polytechnic & Skill College', district: 'Bokaro', code: 'JH-BOK-104', totalStudents: 110, complianceScore: 90.1, status: 'Active', category: 'Polytechnic & Skill Institute' },
  { id: 'inst-05', name: 'Hazaribagh Special Education Academy', district: 'Hazaribagh', code: 'JH-HZB-105', totalStudents: 75, complianceScore: 86.8, status: 'Active', category: 'Special Education Academy' },
];

export const mockStudents: Student[] = [
  {
    id: 'std-001',
    rollNumber: 'INC-2026-001',
    fullName: 'Aarav Sharma',
    age: 16,
    grade: 'Grade 11',
    section: 'A - Science',
    institutionId: 'inst-01',
    institutionName: 'Jamshedpur Special Education & Technical Institute',
    guardianName: 'Rajesh Sharma',
    guardianPhone: '+91 98765 43210',
    guardianEmail: 'rajesh.sharma@example.com',
    emergencyContact: '+91 98765 43211',
    disabilityPercentage: 75,
    udidCardNumber: 'MH14001200800192',
    academicPerformanceScore: 88,
    supportHistoryCount: 14,
    activeAccommodationsCount: 4,
    ilpStatus: 'approved',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-001',
      studentId: 'std-001',
      categories: ['visual'],
      primaryCategory: 'visual',
      severity: 'severe',
      communicationPreference: 'audio',
      learningFormatPreference: 'text_to_speech',
      examinationFormatPreference: 'scribe',
      assistiveTechNeeded: ['Screen Reader (NVDA)', 'Refreshable Braille Display', 'Audio Calculator'],
      classroomAccommodationsNeeded: ['Front row seating', 'High contrast printouts', 'Audio recorded lectures'],
      digitalAccommodationsNeeded: ['Accessible Screen Reader PDFs', 'Dark mode high contrast UI'],
      transportationNeeded: true,
      updatedAt: '2026-08-10',
    },
  },
  {
    id: 'std-002',
    rollNumber: 'INC-2026-002',
    fullName: 'Ananya Deshmukh',
    age: 15,
    grade: 'Grade 10',
    section: 'B - Arts',
    institutionId: 'inst-02',
    institutionName: 'Dr. B.R. Ambedkar National Inclusive Academy, Pune',
    guardianName: 'Priya Deshmukh',
    guardianPhone: '+91 98220 11223',
    guardianEmail: 'priya.d@example.com',
    emergencyContact: '+91 98220 11224',
    disabilityPercentage: 80,
    udidCardNumber: 'MH12009200900481',
    academicPerformanceScore: 92,
    supportHistoryCount: 9,
    activeAccommodationsCount: 3,
    ilpStatus: 'approved',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-002',
      studentId: 'std-002',
      categories: ['hearing', 'speech'],
      primaryCategory: 'hearing',
      severity: 'severe',
      communicationPreference: 'sign_language',
      learningFormatPreference: 'audio_visual',
      examinationFormatPreference: 'digital_accessible',
      assistiveTechNeeded: ['Hearing Aids', 'Real-time Captioning Software', 'ISL Interpreter App'],
      classroomAccommodationsNeeded: ['ISL Sign Language Interpreter', 'Live Captions on Screen'],
      digitalAccommodationsNeeded: ['Subtitled Video Lectures', 'Visual Bell & Alerts'],
      transportationNeeded: false,
      updatedAt: '2026-08-12',
    },
  },
  {
    id: 'std-003',
    rollNumber: 'INC-2026-003',
    fullName: 'Rohan Kulkarni',
    age: 17,
    grade: 'Grade 12',
    section: 'C - Commerce',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    guardianName: 'Suresh Kulkarni',
    guardianPhone: '+91 99300 44556',
    guardianEmail: 'suresh.k@example.com',
    emergencyContact: '+91 99300 44557',
    disabilityPercentage: 60,
    udidCardNumber: 'MH14002200700883',
    academicPerformanceScore: 81,
    supportHistoryCount: 11,
    activeAccommodationsCount: 3,
    ilpStatus: 'active',
    ispStatus: 'approved',
    accessibilityProfile: {
      id: 'ap-003',
      studentId: 'std-003',
      categories: ['mobility'],
      primaryCategory: 'mobility',
      severity: 'moderate',
      communicationPreference: 'standard',
      learningFormatPreference: 'interactive',
      examinationFormatPreference: 'extra_time',
      assistiveTechNeeded: ['Motorized Wheelchair', 'Ergonomic Desk'],
      classroomAccommodationsNeeded: ['Ground floor seating', 'Ramp accessible lab', 'Accessible washroom access'],
      digitalAccommodationsNeeded: ['On-screen keyboard support'],
      transportationNeeded: true,
      updatedAt: '2026-08-14',
    },
  },
  {
    id: 'std-004',
    rollNumber: 'INC-2026-004',
    fullName: 'Diya Patil',
    age: 14,
    grade: 'Grade 9',
    section: 'A - Science',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    guardianName: 'Sunil Patil',
    guardianPhone: '+91 94221 88776',
    guardianEmail: 'sunil.p@example.com',
    emergencyContact: '+91 94221 88777',
    disabilityPercentage: 45,
    udidCardNumber: 'MH31005201000319',
    academicPerformanceScore: 76,
    supportHistoryCount: 7,
    activeAccommodationsCount: 2,
    ilpStatus: 'under_review',
    ispStatus: 'active',
    accessibilityProfile: {
      id: 'ap-004',
      studentId: 'std-004',
      categories: ['learning_difficulties', 'neurodiverse'],
      primaryCategory: 'learning_difficulties',
      severity: 'moderate',
      communicationPreference: 'simplified_text',
      learningFormatPreference: 'simplified_syntax',
      examinationFormatPreference: 'extra_time',
      assistiveTechNeeded: ['Text-Simplifier AI Assistant', 'Read&Write Software'],
      classroomAccommodationsNeeded: ['Extra time on assignments', 'Visual task schedules', 'Quiet study corner'],
      digitalAccommodationsNeeded: ['OpenDyslexic Font mode', 'Break down long paragraphs'],
      transportationNeeded: false,
      updatedAt: '2026-08-15',
    },
  },
];

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: 'sr-101',
    ticketNumber: 'REQ-2026-8801',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionId: 'inst-01',
    serviceType: 'scribe',
    title: 'Certified Scribe Request for Grade 11 Mid-Term Physics & Chemistry Exams',
    description: 'Student requires a certified scribe proficient in Science notation for upcoming mid-term exams starting Aug 25.',
    urgency: 'high',
    status: 'under_review',
    requestedBy: 'Rajesh Sharma (Parent)',
    createdAt: '2026-08-18 10:30',
    updatedAt: '2026-08-18 11:15',
  },
  {
    id: 'sr-102',
    ticketNumber: 'REQ-2026-8802',
    studentId: 'std-002',
    studentName: 'Ananya Deshmukh',
    institutionId: 'inst-02',
    serviceType: 'sign_language_interpreter',
    title: 'ISL Interpreter Request for Annual Science Exhibition',
    description: 'Requires Indian Sign Language interpreter during live project presentations.',
    urgency: 'medium',
    status: 'approved',
    requestedBy: 'Priya Deshmukh (Parent)',
    assignedToStaffName: 'Prof. Smita Joshi (ISL Coordinator)',
    createdAt: '2026-08-16 14:20',
    updatedAt: '2026-08-17 09:00',
  },
  {
    id: 'sr-103',
    ticketNumber: 'REQ-2026-8803',
    studentId: 'std-003',
    studentName: 'Rohan Kulkarni',
    institutionId: 'inst-01',
    serviceType: 'transportation',
    title: 'Wheelchair Accessible Van Request for Daily Campus Transit',
    description: 'Requesting wheelchair-accessible ramp bus pickup from Ghatkopar metro station.',
    urgency: 'medium',
    status: 'in_progress',
    requestedBy: 'Rohan Kulkarni (Student)',
    assignedToStaffName: 'Vijay Shinde (Transport Supervisor)',
    createdAt: '2026-08-12 16:45',
    updatedAt: '2026-08-15 12:00',
  },
];

export const mockExamAccommodations: ExamAccommodation[] = [
  {
    id: 'ea-301',
    examName: 'Mid-Term Board Physics Paper 1',
    subjectCode: 'PHY-101',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionId: 'inst-01',
    examDate: '2026-08-25',
    extraTimeMinutes: 40,
    scribeNeeded: true,
    scribeAssignedName: 'Vikram Mehta (M.Sc Physics)',
    readerNeeded: true,
    interpreterNeeded: false,
    alternativePaperNeeded: false,
    status: 'approved',
    invigilatorNotes: 'Scribe verified. Audio recording permitted in Room 104 Accessibility Lab.',
  },
  {
    id: 'ea-302',
    examName: 'Mathematics Annual Paper',
    subjectCode: 'MATH-202',
    studentId: 'std-002',
    studentName: 'Ananya Deshmukh',
    institutionId: 'inst-02',
    examDate: '2026-08-28',
    extraTimeMinutes: 30,
    scribeNeeded: false,
    readerNeeded: false,
    interpreterNeeded: true,
    alternativePaperNeeded: true,
    status: 'allocated',
    invigilatorNotes: 'Visual question paper provided. ISL interpreter present during instructions.',
  },
];

export const mockAudits: InstitutionAudit[] = [
  {
    id: 'aud-501',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    district: 'Mumbai Suburban',
    auditorId: 'aud-09',
    auditorName: 'Dr. Ramesh Nambiar (Certified Accessibility Auditor)',
    auditDate: '2026-08-05',
    overallScore: 89,
    riskLevel: 'low',
    status: 'verified',
    checklistItems: [
      { id: 'ck-1', category: 'entrance', title: 'Main Entrance Ramp & Tactile Paving', description: 'Ramp slope < 1:12 with continuous handrails and tactile guiding path.', isCompliant: true, score: 9.5 },
      { id: 'ck-2', category: 'digital', title: 'Website & Student Portal Screen Reader Compliance', description: 'WCAG 2.1 AA certified with full keyboard navigation.', isCompliant: true, score: 9.0 },
      { id: 'ck-3', category: 'washroom', title: 'Accessible Gender-Neutral Washrooms', description: 'Grab bars, emergency pull cord, sliding doors on ground & 1st floors.', isCompliant: true, score: 8.5 },
      { id: 'ck-4', category: 'laboratory', title: 'Adjustable Height Science Laboratory Benches', description: 'Motorized height adjustable benches for wheelchair users.', isCompliant: true, score: 9.0 },
      { id: 'ck-5', category: 'emergency', title: 'Strobe Light & Tactile Emergency Alarms', description: 'Visual strobe lights in all classrooms and auditory chime in corridors.', isCompliant: false, score: 5.0, notes: 'Missing strobe light in 3rd floor chemistry lab.' },
    ],
  },
  {
    id: 'aud-502',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    district: 'Nagpur',
    auditorId: 'aud-12',
    auditorName: 'Sunita Rao (District Inspector)',
    auditDate: '2026-08-11',
    overallScore: 68,
    riskLevel: 'high',
    status: 'submitted',
    checklistItems: [
      { id: 'ck-201', category: 'entrance', title: 'Main Entrance Ramp', description: 'Steep ramp lacking braille signage.', isCompliant: false, score: 4.0 },
      { id: 'ck-202', category: 'washroom', title: 'Accessible Washrooms', description: 'Locked washroom converted to storage.', isCompliant: false, score: 2.0 },
    ],
  },
];

export const mockComplianceRequirements: ComplianceRequirement[] = [
  { id: 'cr-01', code: 'RPWD-SEC-16', title: 'Duty of Educational Institutions regarding Inclusive Education', legalReference: 'Rights of Persons with Disabilities Act 2016 - Section 16', category: 'physical_access', mandatoryLevel: 'essential', evidenceType: 'audit_report' },
  { id: 'cr-02', code: 'RPWD-SEC-17', title: 'Specific measures to promote and facilitate inclusive education', legalReference: 'RPWD Act 2016 - Section 17', category: 'academic_accommodation', mandatoryLevel: 'essential', evidenceType: 'document' },
  { id: 'cr-03', code: 'UGC-A11Y-2023', title: 'Guidelines for Accessible Higher Education & Digital Infrastructure', legalReference: 'UGC Notification 2023', category: 'digital_access', mandatoryLevel: 'essential', evidenceType: 'certificate' },
];

export const mockComplianceRecords: InstitutionComplianceRecord[] = [
  { id: 'icr-1', institutionId: 'inst-01', institutionName: 'Government Institute of Inclusive Science, Mumbai', requirementId: 'cr-01', requirementTitle: 'Duty of Educational Institutions regarding Inclusive Education', status: 'compliant', verifiedBy: 'Auditor Nambiar', verifiedAt: '2026-08-06' },
  { id: 'icr-2', institutionId: 'inst-01', institutionName: 'Government Institute of Inclusive Science, Mumbai', requirementId: 'cr-03', requirementTitle: 'Guidelines for Accessible Higher Education & Digital Infrastructure', status: 'compliant', verifiedBy: 'Auditor Nambiar', verifiedAt: '2026-08-06' },
  { id: 'icr-3', institutionId: 'inst-03', institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur', requirementId: 'cr-01', requirementTitle: 'Duty of Educational Institutions regarding Inclusive Education', status: 'non_compliant', correctiveActionPlan: 'Construct standard 1:12 ramp and install braille handrails.', deadline: '2026-09-30' },
];

export const mockIncidents: IncidentReport[] = [
  {
    id: 'inc-901',
    caseNumber: 'INC-2026-041',
    category: 'accessibility_denial',
    isAnonymous: false,
    reporterId: 'std-003',
    reporterRole: 'student',
    victimStudentId: 'std-003',
    institutionId: 'inst-01',
    title: 'Elevator Out of Service Blocking Access to 3rd Floor Computer Lab',
    description: 'Elevator B in Block C has been broken for 4 days, preventing wheelchair users from attending practical exams.',
    location: 'Block C Elevator B',
    dateOfIncident: '2026-08-17',
    severity: 'severe',
    status: 'under_investigation',
    investigatingOfficerName: 'Er. Rajesh Varma (Facility Head)',
    createdAt: '2026-08-17 11:30',
  },
  {
    id: 'inc-902',
    caseNumber: 'INC-2026-042',
    category: 'bullying',
    isAnonymous: true,
    institutionId: 'inst-03',
    title: 'Verbal Harassment regarding Hearing Aid Usage',
    description: 'Reported inappropriate mocking of a hearing impaired student during lunch break.',
    location: 'Cafeteria Wing A',
    dateOfIncident: '2026-08-15',
    severity: 'moderate',
    status: 'action_taken',
    investigatingOfficerName: 'Dr. Meena Iyer (Counselor)',
    resolutionSummary: 'Counseling session conducted with class students. Awareness drive scheduled.',
    createdAt: '2026-08-15 15:10',
  },
];

export const mockPolicies: GovernancePolicy[] = [
  { id: 'pol-01', policyNumber: 'POL-A11Y-2026-01', title: 'Universal Accommodation & Scribe Guidelines 2026', category: 'exam_rules', effectiveDate: '2026-01-01', version: '2.4', approvedBy: 'State Board Governance Council', status: 'active' },
  { id: 'pol-02', policyNumber: 'POL-A11Y-2026-02', title: 'Digital Learning Material Accessibility Policy', category: 'accessibility_standard', effectiveDate: '2026-03-15', version: '1.2', approvedBy: 'Department of Inclusive Education', status: 'active' },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: 'air-1',
    type: 'accessibility_gap',
    title: 'High Exam Scribe Demand Predicted for Upcoming Mid-Terms',
    description: 'AI model detected 28 pending scribe requests in Mumbai District. Recommended assigning 12 additional certified scribes to prevent bottlenecks.',
    institutionId: 'inst-01',
    institutionName: 'Government Institute of Inclusive Science, Mumbai',
    confidenceScore: 94,
    suggestedAction: 'Auto-allocate 12 verified postgraduate volunteer scribes to exam room 104 & 105.',
    status: 'pending_review',
    createdAt: '2026-08-18 08:00',
  },
  {
    id: 'air-2',
    type: 'risk_alert',
    title: 'Compliance Risk Alert: Elevator Maintenance Delay in Nagpur School',
    description: 'Chhatrapati Shivaji Secondary School compliance score fell to 68%. Elevated risk of RPWD Section 16 non-compliance notice.',
    institutionId: 'inst-03',
    institutionName: 'Chhatrapati Shivaji Inclusive Higher Secondary School, Nagpur',
    confidenceScore: 91,
    suggestedAction: 'Issue immediate corrective action notice with 15-day remediation deadline.',
    status: 'pending_review',
    createdAt: '2026-08-17 16:30',
  },
];

export const mockNotifications: NotificationItem[] = [
  { id: 'notif-1', title: 'Scribe Request Approved', message: 'Your scribe request for Physics Paper 1 has been approved.', type: 'success', targetRoles: ['student', 'parent'], timestamp: '10 mins ago', isRead: false },
  { id: 'notif-2', title: 'Audit Report Submitted', message: 'Annual Accessibility Audit for Institute #101 is now available for review.', type: 'info', targetRoles: ['auditor', 'principal', 'institution_admin', 'district_officer'], timestamp: '1 hour ago', isRead: false },
  { id: 'notif-3', title: 'Action Required: Ramp Inspection', message: 'Remediation deadline for Ramp signage in Block B expires in 3 days.', type: 'warning', targetRoles: ['institution_admin', 'accessibility_coordinator'], timestamp: '3 hours ago', isRead: true },
];

export const mockProfessionals = [
  {
    id: 'prof-1',
    name: 'Priya Kumari',
    email: 'priya.kumari@sakshampath.org',
    phone: '+91 98351 22340',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    district: 'Ranchi',
    state: 'Jharkhand',
    primaryService: 'certified_scribe' as const,
    otherServices: ['lesson_reader' as const, 'exam_reader' as const],
    qualification: 'M.A. English & RCI Certified Inclusion Assistant',
    experienceYears: 4,
    languages: ['Hindi', 'English'],
    organization: 'Jharkhand Disability Support Council',
    certificationDetails: 'RCI Registration #RCI-A11Y-2022-894; UGC Certified Scribe Roster',
    status: 'verified' as const,
    rating: 4.9,
    completedSessions: 38,
    supportHours: 114,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableHours: '09:00 AM - 05:00 PM',
    serviceArea: 'Ranchi Urban & Doranda',
    preference: 'both' as const,
    registeredAt: '2025-09-12',
  },
  {
    id: 'prof-2',
    name: 'Rahul Kumar',
    email: 'rahul.kumar@sakshampath.org',
    phone: '+91 94311 88721',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    district: 'Ranchi',
    state: 'Jharkhand',
    primaryService: 'sign_language_interpreter' as const,
    otherServices: ['exam_reader' as const, 'accessibility_support_assistant' as const],
    qualification: 'Diploma in Indian Sign Language Interpretation (DISLI - ISLRTC)',
    experienceYears: 5,
    languages: ['Hindi', 'English', 'Indian Sign Language'],
    organization: 'Jharkhand Deaf Association',
    certificationDetails: 'ISLRTC Certified Level-B Interpreter #ISL-2021-419',
    status: 'verified' as const,
    rating: 4.8,
    completedSessions: 52,
    supportHours: 156,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday'],
    availableHours: '08:00 AM - 06:00 PM',
    serviceArea: 'Ranchi, Morabadi & Namkum',
    preference: 'both' as const,
    registeredAt: '2025-06-18',
  },
  {
    id: 'prof-3',
    name: 'Anjali Devi',
    email: 'anjali.devi@sakshampath.org',
    phone: '+91 91223 44556',
    avatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    district: 'Khunti',
    state: 'Jharkhand',
    primaryService: 'assistant_teacher' as const,
    otherServices: ['special_educator' as const, 'lesson_reader' as const],
    qualification: 'B.Ed in Special Education (Learning Disabilities)',
    experienceYears: 2,
    languages: ['Hindi'],
    organization: 'Khunti Rural Inclusive Learning Center',
    certificationDetails: 'RCI Provisional Registration #RCI-PR-2024-112',
    status: 'pending_verification' as const,
    rating: 4.7,
    completedSessions: 12,
    supportHours: 36,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableHours: '10:00 AM - 04:00 PM',
    serviceArea: 'Khunti District Schools',
    preference: 'in_person' as const,
    registeredAt: '2026-08-15',
  },
  {
    id: 'prof-4',
    name: 'Vikram Soren',
    email: 'vikram.soren@sakshampath.org',
    phone: '+91 97712 33490',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    district: 'Dhanbad',
    state: 'Jharkhand',
    primaryService: 'certified_scribe' as const,
    otherServices: ['accessibility_support_assistant' as const, 'lesson_reader' as const],
    qualification: 'M.Sc. Mathematics & Certified Assistive Scribe',
    experienceYears: 3,
    languages: ['Hindi', 'English', 'Santhali'],
    organization: 'Dhanbad Inclusive Education Mission',
    certificationDetails: 'State Board Approved STEM Scribe #DHN-SC-881',
    status: 'verified' as const,
    rating: 4.9,
    completedSessions: 29,
    supportHours: 87,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
    availableHours: '09:00 AM - 05:00 PM',
    serviceArea: 'Dhanbad & Jharia',
    preference: 'both' as const,
    registeredAt: '2025-11-04',
  },
  {
    id: 'prof-5',
    name: 'Sunita Mahato',
    email: 'sunita.mahato@sakshampath.org',
    phone: '+91 94701 55667',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    district: 'East Singhbhum (Jamshedpur)',
    state: 'Jharkhand',
    primaryService: 'lesson_reader' as const,
    otherServices: ['assistant_teacher' as const, 'exam_reader' as const],
    qualification: 'M.A. Education & Braille Transcriber',
    experienceYears: 4,
    languages: ['Hindi', 'Bengali', 'English'],
    organization: 'Jamshedpur Accessibility League',
    certificationDetails: 'National Institute for Visually Handicapped (NIVH) Certificate #NIVH-2023-55',
    status: 'verified' as const,
    rating: 4.8,
    completedSessions: 21,
    supportHours: 63,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    availableHours: '08:30 AM - 04:30 PM',
    serviceArea: 'Jamshedpur & Bistupur',
    preference: 'both' as const,
    registeredAt: '2025-08-20',
  },
];

export const mockSupportRequests = [
  {
    id: 'req-001',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionId: 'inst-01',
    institutionName: 'Ranchi Government Inclusive Model High School',
    supportType: 'certified_scribe' as const,
    subjectOrEvent: 'Grade 10 Physics Mid-Term Board Exam',
    date: '2026-08-28',
    time: '10:00 AM – 01:00 PM',
    durationHours: 3,
    location: 'Exam Hall 3, Ranchi High School, Kanke Road',
    district: 'Ranchi',
    languagePreference: ['Hindi', 'English'],
    additionalRequirements: 'High-contrast STEM diagrams & mathematical equation transcribing experience required.',
    status: 'pending' as const,
    assignedProfessionalId: 'prof-1',
    assignedProfessionalName: 'Priya Kumari',
    createdAt: '2026-08-20',
  },
  {
    id: 'req-002',
    studentId: 'std-002',
    studentName: 'Diya Patel',
    institutionId: 'inst-01',
    institutionName: 'Ranchi Government Inclusive Model High School',
    supportType: 'sign_language_interpreter' as const,
    subjectOrEvent: 'Higher Secondary Chemistry Lab Workshop & Practical Lecture',
    date: '2026-08-29',
    time: '11:00 AM – 02:00 PM',
    durationHours: 3,
    location: 'Chemistry Lab 2, Ranchi High School',
    district: 'Ranchi',
    languagePreference: ['Indian Sign Language', 'Hindi'],
    additionalRequirements: 'Sign language interpretation for chemical safety procedures and teacher instructions.',
    status: 'pending' as const,
    assignedProfessionalId: 'prof-2',
    assignedProfessionalName: 'Rahul Kumar',
    createdAt: '2026-08-21',
  },
  {
    id: 'req-003',
    studentId: 'std-003',
    studentName: 'Rohan Verma',
    institutionId: 'inst-02',
    institutionName: 'St. Xavier Inclusive College, Ranchi',
    supportType: 'lesson_reader' as const,
    subjectOrEvent: 'Civics & Indian Constitution Chapter Study Session',
    date: '2026-08-30',
    time: '02:00 PM – 04:00 PM',
    durationHours: 2,
    location: 'Library Quiet Room B, St. Xavier College, Ranchi',
    district: 'Ranchi',
    languagePreference: ['Hindi', 'English'],
    additionalRequirements: 'Audio reading of text notes and highlighting key case laws.',
    status: 'matching' as const,
    createdAt: '2026-08-21',
  },
  {
    id: 'req-004',
    studentId: 'std-004',
    studentName: 'Sneha Soren',
    institutionId: 'inst-03',
    institutionName: 'Dhanbad Central Inclusive Secondary School',
    supportType: 'certified_scribe' as const,
    subjectOrEvent: 'Mathematics Grade 12 Calculus Terminal Test',
    date: '2026-09-02',
    time: '09:30 AM – 12:30 PM',
    durationHours: 3,
    location: 'Room 102, Dhanbad Central School',
    district: 'Dhanbad',
    languagePreference: ['Hindi', 'English', 'Santhali'],
    additionalRequirements: 'Formula dictation and step-by-step writing.',
    status: 'pending' as const,
    assignedProfessionalId: 'prof-4',
    assignedProfessionalName: 'Vikram Soren',
    createdAt: '2026-08-21',
  },
];

export const mockAssignments = [
  {
    id: 'asg-101',
    requestId: 'req-001',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionName: 'Ranchi Government Inclusive Model High School',
    supportType: 'certified_scribe' as const,
    subjectOrEvent: 'Grade 10 Physics Mid-Term Board Exam',
    date: '2026-08-28',
    time: '10:00 AM – 01:00 PM',
    durationHours: 3,
    location: 'Exam Hall 3, Ranchi High School, Kanke Road',
    status: 'accepted' as const,
    professionalId: 'prof-1',
    professionalName: 'Priya Kumari',
    compensation: '₹1,200 (State Sponsored)',
  },
  {
    id: 'asg-102',
    requestId: 'req-002',
    studentId: 'std-002',
    studentName: 'Diya Patel',
    institutionName: 'Ranchi Government Inclusive Model High School',
    supportType: 'sign_language_interpreter' as const,
    subjectOrEvent: 'Higher Secondary Chemistry Lab Workshop',
    date: '2026-08-29',
    time: '11:00 AM – 02:00 PM',
    durationHours: 3,
    location: 'Chemistry Lab 2, Ranchi High School',
    status: 'confirmed' as const,
    professionalId: 'prof-2',
    professionalName: 'Rahul Kumar',
    compensation: '₹1,500 (RCI Standard)',
  },
  {
    id: 'asg-100',
    requestId: 'req-000',
    studentId: 'std-001',
    studentName: 'Aarav Sharma',
    institutionName: 'Ranchi Government Inclusive Model High School',
    supportType: 'lesson_reader' as const,
    subjectOrEvent: 'Biology Cell Structure Reading & Concept Review',
    date: '2026-08-16',
    time: '03:00 PM – 05:00 PM',
    durationHours: 2,
    location: 'Library Inclusion Pod',
    status: 'completed' as const,
    professionalId: 'prof-1',
    professionalName: 'Priya Kumari',
    compensation: '₹800 (Completed)',
  },
];

